# -*- coding: utf-8 -*-
"""gradient_descent_scratch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NzBLr6MXjPSMNIb_T7KSWEcIXq4Uxjm4

Testing and observing read in variations.
"""

import pandas as pd

data = pd.read_csv("/content/clean_weather.csv")
data = data.ffill() # forward fill missing data

data.head(5)

data.describe()

data.columns

data_M = data.to_numpy()

data_M.shape

data2 = pd.read_csv("/content/clean_weather.csv", index_col=0)
data2 = data.ffill() # forward fill missing data

data2.head(5)

data2.index

data2.columns

data_M2 = data2.to_numpy()

data_M2.shape

"""I didn't initially assign the index_col so row numbers were used and this lead to an additional data column."""



















